nuitka \
  --standalone \
  --macos-create-app-bundle \
  --enable-plugin=pyside6 \
  --macos-app-icon=jdxi_icon.icns \
  --include-package=jdxi_editor \
  --include-package=rtmidi \
  --include-data-dir=resources=resources \
  --output-dir=dist run_editor.py