JDXI_HEIGHT = 400

JDXI_WIDTH = 1000

JDXI_WHITE_KEY_HEIGHT = 127

JDXI_KEYBOARD_WIDTH = 800

JDXI_MARGIN = 15

JDXI_DISPLAY_X = JDXI_MARGIN
# Title above display (moved down)
JDXI_TITLE_X = JDXI_DISPLAY_X
JDXI_TITLE_Y = JDXI_MARGIN
# LED display area (enlarged for 2 rows)
JDXI_DISPLAY_Y = JDXI_TITLE_Y + 40  # 40 gives some space for the title
JDXI_DISPLAY_WIDTH = 255
JDXI_DISPLAY_HEIGHT = 70
