from __future__ import annotations

from jdxi_editor.midi.sysex.request.hex import JDXISysExHex

RQ11_COMMAND_HEADER = (
    f"{JDXISysExHex.JDXI_HEADER} {JDXISysExHex.RQ1_COMMAND_11}"
)
TEMPORARY_PROGRAM_RQ11_HEADER = (
    f"{RQ11_COMMAND_HEADER} {JDXISysExHex.TEMPORARY_PROGRAM_AREA}"
)
TEMPORARY_TONE_RQ11_HEADER = (
    f"{RQ11_COMMAND_HEADER} {JDXISysExHex.TEMPORARY_TONE_AREA}"
)
PROGRAM_COMMON_RQ11_HEADER = (
    f"{TEMPORARY_PROGRAM_RQ11_HEADER} {JDXISysExHex.PROGRAM_COMMON_AREA}"
)
IGNORED_KEYS = {
    "TEMPORARY_AREA", "SYNTH_TONE", "TONE_NAME_1", "TONE_NAME_2", "TONE_NAME_3", "TONE_NAME_4", "TONE_NAME_5",
    "TONE_NAME_6", "TONE_NAME_7", "TONE_NAME_8", "TONE_NAME_9", "TONE_NAME_10", "TONE_NAME_11", "TONE_NAME_12",
    "PARTIAL_NAME_1", "PARTIAL_NAME_2", "PARTIAL_NAME_3", "PARTIAL_NAME_4", "PARTIAL_NAME_5", "PARTIAL_NAME_6",
    "PARTIAL_NAME_7", "PARTIAL_NAME_8", "PARTIAL_NAME_9", "PARTIAL_NAME_10", "PARTIAL_NAME_11", "PARTIAL_NAME_12",
    "JD_XI_HEADER", "ADDRESS", "TONE_NAME",
}
SYNTH_PARTIAL_MAP = {
    "TONE_COMMON": 0,
    "PARTIAL_1": 1,
    "PARTIAL_2": 2,
    "PARTIAL_3": 3,
    "TONE_PARTIAL_1": 1,
    "TONE_PARTIAL_2": 2,
    "TONE_PARTIAL_3": 3,
}
