from __future__ import annotations

from jdxi_editor.midi.sysex.request.hex import JDXISysExHex

RQ11_COMMAND_HEADER = (
    f"{JDXISysExHex.JDXI_HEADER} {JDXISysExHex.RQ1_COMMAND_11}"
)
TEMPORARY_PROGRAM_RQ11_HEADER = (
    f"{RQ11_COMMAND_HEADER} {JDXISysExHex.TEMPORARY_PROGRAM_AREA}"
)
TEMPORARY_TONE_RQ11_HEADER = (
    f"{RQ11_COMMAND_HEADER} {JDXISysExHex.TEMPORARY_TONE_AREA}"
)
PROGRAM_COMMON_RQ11_HEADER = (
    f"{TEMPORARY_PROGRAM_RQ11_HEADER} {JDXISysExHex.PROGRAM_COMMON_AREA}"
)
