from __future__ import annotations

from jdxi_editor.midi.sysex.request.hex import JDXISysExHex
from jdxi_editor.midi.sysex.sections import SysExSection

RQ11_COMMAND_HEADER = f"{JDXISysExHex.JDXI_HEADER} {JDXISysExHex.RQ1_COMMAND_11}"
SYSTEM_RQ11_HEADER = f"{RQ11_COMMAND_HEADER} {JDXISysExHex.SYSTEM_AREA}"
TEMPORARY_PROGRAM_RQ11_HEADER = (
    f"{RQ11_COMMAND_HEADER} {JDXISysExHex.TEMPORARY_PROGRAM_AREA}"
)
TEMPORARY_TONE_RQ11_HEADER = f"{RQ11_COMMAND_HEADER} {JDXISysExHex.TEMPORARY_TONE_AREA}"
PROGRAM_COMMON_RQ11_HEADER = (
    f"{TEMPORARY_PROGRAM_RQ11_HEADER} {JDXISysExHex.PROGRAM_COMMON_AREA}"
)
IGNORED_KEYS = {
    SysExSection.TEMPORARY_AREA,
    "TONE_NAME_1",
    "TONE_NAME_2",
    "TONE_NAME_3",
    "TONE_NAME_4",
    "TONE_NAME_5",
    "TONE_NAME_6",
    "TONE_NAME_7",
    "TONE_NAME_8",
    "TONE_NAME_9",
    "TONE_NAME_10",
    "TONE_NAME_11",
    "TONE_NAME_12",
    "PARTIAL_NAME_1",
    "PARTIAL_NAME_2",
    "PARTIAL_NAME_3",
    "PARTIAL_NAME_4",
    "PARTIAL_NAME_5",
    "PARTIAL_NAME_6",
    "PARTIAL_NAME_7",
    "PARTIAL_NAME_8",
    "PARTIAL_NAME_9",
    "PARTIAL_NAME_10",
    "PARTIAL_NAME_11",
    "PARTIAL_NAME_12",
    SysExSection.JD_XI_HEADER,
    SysExSection.ADDRESS,
    SysExSection.TONE_NAME,
}
SYNTH_PARTIAL_MAP = {
    "COMMON": 0,
    "MODIFY": 0,
    "PARTIAL_1": 1,
    "PARTIAL_2": 2,
    "PARTIAL_3": 3,
    "TONE_PARTIAL_1": 1,
    "TONE_PARTIAL_2": 2,
    "TONE_PARTIAL_3": 3,
}
