name: jdxi-editor
version: '0.9.0'
summary: MIDI Editor for Roland JD-Xi Synthesizer
description: |
  JD-Xi Editor is a comprehensive MIDI editor and toolkit for the 
  Roland JD-Xi synthesizer. It provides an intuitive graphical interface 
  for editing patches, managing presets, and controlling the synthesizer 
  in real-time.
  
  Features:
  - Edit Digital, Analog, and Drum Kit patches
  - Real-time parameter control via MIDI
  - Preset management and organization
  - MIDI file playback and recording
  - Intuitive Qt-based user interface

grade: stable
confinement: strict
base: core22
architectures:
  - build-on: amd64

apps:
  jdxi-editor:
    command: bin/jdxi-editor
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - opengl
      - audio-playback
      - audio-record
      - raw-usb
      - hardware-observe
      - network
    environment:
      QT_QPA_PLATFORM: xcb
      DISABLE_WAYLAND: "1"

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  jdxi-editor:
    plugin: python
    source: .
    python-packages:
      - PySide6>=6.8.1.1
      - PySide6-Addons>=6.8.1.1
      - PySide6-Essentials>=6.8.1.1
      - python-rtmidi>=1.5.8
      - mido>=1.3.3
      - numpy
      - matplotlib>=3.9.4
      - pillow>=11.1.0
      - Pypubsub>=4.0.3
      - QtAwesome>=1.3.1
      - QtPy>=2.4.3
      - pyaudio>=0.2.14
      - tabulate>=0.9.0
    build-packages:
      - python3-dev
      - python3-pip
      - libasound2-dev
      - libjack-jackd2-dev
      - portaudio19-dev
      - build-essential
      - pkg-config
    stage-packages:
      - libasound2
      - libjack-jackd2-0
      - libportaudio2
      - libegl1
      - libgl1
      - libglib2.0-0
      - libxkbcommon0
      - libxcb-cursor0
      - libxcb-icccm4
      - libxcb-keysyms1
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xkb1
      - libfontconfig1
      - libfreetype6
      - libdbus-1-3
    override-build: |
      craftctl default
      # Copy resources
      mkdir -p $CRAFT_PART_INSTALL/share/jdxi-editor
      cp -r resources $CRAFT_PART_INSTALL/share/jdxi-editor/
      # Create launcher script
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/jdxi-editor << 'EOF'
      #!/bin/bash
      export PYTHONPATH="$SNAP/lib/python3.10/site-packages:$PYTHONPATH"
      exec python3 -m jdxi_editor.main "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/jdxi-editor

  desktop-integration:
    plugin: dump
    source: .
    organize:
      resources/jdxi_icon_512.png: share/icons/hicolor/512x512/apps/jdxi-editor.png
      resources/jdxi_icon.png: share/icons/hicolor/256x256/apps/jdxi-editor.png
    stage:
      - share/icons/hicolor/*/apps/jdxi-editor.png
    after: [jdxi-editor]

