# .github/workflows/docs.yml
name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements-docs.txt
    
    - name: Build documentation
      run: |
        cd doc
        sphinx-build -b html . _build/html
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./doc/_build/html

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main' 